Downgrade bash to fix solaris issue
chef/omnibus-toolchain pull request #260
Opened 2023-11-10 04:54 UTC by poorndm

## Description

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have run the pre-merge tests locally and they pass.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] If `Gemfile.lock` has changed, I have used `--conservative` to do it and included the full output in the Description above.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

2023-11-10 08:44 UTC, anandhapadmanabhan approved these changes

2023-11-16 05:46 UTC, poorndm commented
https://buildkite.com/chef-canary/chef-omnibus-toolchain-main-omnibus-adhoc-canary/builds/75 - failing on el-6

2023-11-16 10:26 UTC, poorndm commented
> @poorndm Request you to get the PR approved and merged as soon as possible. We will follow up with chef 18 changes after that.

@rahulgoel1 While the build is green on Solaris, it seems to be failing on other platforms. Ensuring a successful build across all platforms is crucial for a stable release of the omnibus-toolchain version. We are working on addressing the issues on the other platforms.

2023-11-22 14:28 UTC, tpowell-progress requested changes

2023-11-22 14:28 UTC, tpowell-progress commented on Gemfile
> +gem 'unf_ext', '0.0.8'
We want the latest `'0.0.8'` which is `'0.0.8.2'` and we should also do pessimistic lock `'~> 0.0.8.2'`

2023-11-22 14:54 UTC, tpowell-progress commented on Gemfile
> +gem 'unf_ext', '0.0.8'
See diff for [v0.0.8 vs v0.0.8.2](https://github.com/knu/ruby-unf_ext/compare/v0.0.8...v0.0.8.2)

2023-12-29 06:14 UTC, closed without merging

2023-12-29 06:14 UTC, poorndm commented
Duplicate of  https://github.com/chef/omnibus-toolchain/pull/271